### ISSUE TITLE
the following endpoint https://www.omicsdi.org:443/ws/dataset/getAll

### ISSUE THREAD

**Issue by ypriverol** [OmicsDI/ddi-web-service#70]
The following endpoint https://www.omicsdi.org:443/ws/dataset/getAll provide no results. Can you update the documentation or let me know what it does?

**Comment by mindcrusher11** [comment]
It will not return any results in browser only as stream in code as it return all records.

**Comment by ypriverol** [comment]
Can you put an example with curl for example? What is this stream protobuf?
