### ISSUE TITLE
Remove / Hide some entry points from Swagger 

### ISSUE THREAD

**Issue by ypriverol** [OmicsDI/ddi-web-service#71]
It does not make sense to have some endpoints highlighted in the documentation if they will not be use by external users, only by the Web Application. 

Please remove from swagger the following sections: 

- Enrichment
- feedback 
- dblucenemapping

**Comment by mindcrusher11** [comment]
will update

**Comment by mindcrusher11** [comment]
Updated and deployed to production

**Comment by ypriverol** [comment]
Really great.
